### ISSUE TITLE
stringsStringsStrings example is incomplete

### ISSUE THREAD

**Issue by pentacular** [tc39/proposal-type-annotations#128]
```function stringsStringStrings(p1: string, p2?: string, p3?: string, p4 = "test"): string {```

is missing the type annotation for p4, which makes the interaction between type annotation and defaults obscure.

Should it be ```p4?:string = "test"``` or ```p4 = "test"?:string```.

I guess it's the first case, but it would be nice to make this obvious. :)

**Comment by orta** [comment]
This sample is legal [TypeScript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAZygJxmA5sgyuzLfDbZACgAcBGALhQOwBpEKAmAfjtRK2YoGZO9HnwAsiALyIARFACmqaQEouDLIgDeAWABQiRGjlQQaJNOm6AvkA) or Flow today. Any type system which has inference and an understanding of how JavaScript arguments work should be able to handle creating a type for `p4` by looking at the type from the default value for that param 👍🏻

**Comment by pentacular** [comment]
Yes, but this is a proposal for extending syntax.

So why not show how the syntax would be extended for case, given this proposal?
