### ISSUE TITLE
Re-deploy site to github pages

### ISSUE THREAD

**Issue by shayneo** [tc39/proposal-type-annotations#139]
I first encountered this proposal at this github pages url `https://giltayar.github.io/proposal-types-as-comments/`

Looks like the repo got transferred over from @giltayar to the offical tc39 org, and the github pages site got blown away in the process.

I know it's not super important, but thought the site was well done and it was helpful (at least to me) for groking the proposal.

Looks like all the code is still there, would be cool if the site got re deployed 😄

**Comment by ljharb** [comment]
It is still up, it's just moved to https://tc39.es/proposal-type-annotations/.

Github doesn't preserve redirects for both the repo and also the pages site.
