### ISSUE TITLE
Disagree with the proposal

### ISSUE THREAD

**Issue by vaynevayne** [tc39/proposal-type-annotations#182]
ts 就是一个垃圾, 每天写 ts 的代码比写 js 还多,  天天要加班
不同意合并到 js 里

**Comment by pan93412** [comment]
> TS is just garbage, writing TS code every day is even more than writing JS, and having to work overtime every day. I don't agree to merge it into JS.

Translation for reference.

**Comment by bradzacher** [comment]
I'm going to go ahead and close this as it doesn't add anything at all to the discussion.

 Please refrain from creating new issues unless you have some constructive criticism for the proposal.
