### ISSUE TITLE
return type inference

### ISSUE THREAD

**Issue by y-nk** [tc39/proposal-type-annotations#51]
Introducing types in comments would probably introduce returned type inference as well (in the long run), which creates the need for more things like type guards and such to be able to analyze correctly the returned types, arguably tying up typings as to what Typescript thinks is a good type system. This somehow brings Microsoft monopoly into JavaScript, excluding other type systems considerations on what typing should be.

---

This feature already exists as part of the tsc and I would rather keep it that way. There's no value in bringing tsc's concerns (which are "types") into JavaScript (a non strictly typed language) and it would definitely change the paradigm of JavaScript as we know it, from how it's used daily to how it's taught in schools.

You could argue it's all optional, but let's face it, with this passing in the spec it'll become a standard sooner or later.

**Comment by giltayar** [comment]
The spec does not define what the type system is, and ignores types completely. As such, it was carefully designed to support both TypeScript _and_ Flow, and to support any type system you wish to add to JavaScript. And while it was designed to be mostly backward compatible with TypeScript and Flow, you can use it to add any type system you design to JavaScript, as long as it conforms to the rules defined in this proposal.

While we could ignore the fact that a substantial part of the JS codebase is today TS (for better or worse) just because "we are afraid that MS will monopolize JavaScript" will mean that many developers who want the benefits of type safety will be coding in TS, and thus using an MS language. This proposal mends this rift: it allows a peaceful co-existence between JavaScript and languages like TS and Flow that add type systems to it.

**Comment by y-nk** [comment]
i'm not sure this the case tho. by adding a "TS looking/compatible" type system in Javascript, it will inevitably pull the caveats of said type system you based your proposal on with it and will require more of this type system's features (type guards, let's say, to pick one of many - which arent compatible in Flow) on the go to overcome the difficulties/uncertainties of using a type system... and in the end it'll bring a "dominantly TS looking implementation" to the rank of worldwide standard.

It can be argued that we can plug in "all compatible type system you want" they'll all have to look like TS in the end, since the original proposal is based on it... and then, what for the non compatible type systems out there? what if TS or Flow decide to add a feature which sides against your standard? what will be the decision between follow TS or cut loose and break compatibility?

Imho if you start like this (by basing your work on proprietary existing work), once this "Flow/TS lookalike" standard will be settled it'll be too difficult to get away from it and remain unbiased over time (driven by TS innovations).

I did not mention Flow because the development seems on hold for quite some time, and also because the champion of this proposal comes from Microsoft as well but tbh it doesn't really matter between Flow and TS, the issue remains the same: for a proprietary tech to elevate as an open standard takes the owner to let go of it.

**Comment by DanielRosenwasser** [comment]
I have to admit, I *think* I understand some of the concerns you've mentioned, but I am confused because I don't understand how they relate to the issue title. Can you provide a specific use-case around a snippet of code and what the concerns are?

**Comment by y-nk** [comment]
@DanielRosenwasser i think i got carried in a deeper meaning of my initial issue, sorry for that 😅

**My initial comment** was touching the surface of my reflexion with an argument such as "it is clear that adding types will implicitly require to add more features which would need to be taken from the "inspiration" projects (typescript, flow) such as automatic inferred return types or type guards (also, control flow analysis).

When you think of types, if you only have a feature manually parameters types it would make no sense at all. The power and convenience of typing comes from type inference and control flow analysis, which are the heart of the Typescript "engine" ; type guards are a important part of it as well since they are here to compensate and guide the control flow analysis when it fails to infer properly by itself. in short if you want a type system, those are implicitly required.

**My followup comment** was that, bringing these missing pieces will make the whole proposal look at 90% like TS because we would need to "take" all which makes TS what it is ; then the proposal could rather be seen as "extracting a subset of TS" (called _Typescript in comments_, since TS already allows for types in comments) and propose it as a tc39 "open standard".

I understand the standing point of being a "compatible" standard ; I also believe tc39 has greater authority on the JavaScript language than the Typescript crew does (since the TS team moto is not to break JS in any way), but it brings the question of future disagreement between tc39 and TS team as well, because there would clear change of dynamics : **the tc39 would take lead on a Typescript compatible open standard on JavaScript typing and the Microsoft team should follow those specs.**

_In the same way_, when the folks at Babel implemented and championned optional chaining, it was their implementation but then when it was elevated and validated by tc39, it became a JavaScript standard and babel people had to _follow_ the spec.

Does that make it clearer? Maybe the topic should be renamed?

**Comment by edmundmunday** [comment]
I think this speaks to a wider conversation around how "deep" such a potential type implementation in JS should go. While I am an advocate for this concept, I personally think it needs to be kept very "light touch" in line with the spirit of JS historically.

Things like TS and Flow are still going to exist if you want "heavy-duty" type support with more complex functionality. Anything implemented in the language should be high-level and relatively unopinionated.

If that means less "perfect" compat with things like TS or Flow, I think it should be up to those tools to **themselves** work with the unopinionated standard, not the other way around.

**Comment by rezonant** [comment]
As best I can tell this proposal preserves and does not extend the existing semantics of JavaScript by design. 

What value does return type inference provide outside of the context of the type checker solution you are using? The type annotations here have no inherent semantic meaning, only the meaning that the type checker gives I (whichever one you choose to use if any)

I don't see the reason inference necessarily needs to be part of this proposal or to be defined at the language level at all.

**Comment by y-nk** [comment]
honestly @rezonant i see no value in a type checker which has only manual typing. it's as prone to error as if there were no types and does not prevent any runetime errors since it's a metadata level typing information. if anything it just adds unnecessary amount of comment blocks to the downloaded script file, which is another downside.

**Comment by y-nk** [comment]
@edmundmunday I agree with you, it's probably a wider discussion and as well, agree that type systems are an interesting feature _and_ that it should be kept light to fit the JS mindset.

That said, I don't see _the value_ of a type system which wouldn't provide any intelligence when it comes to the typings.

The goal is to keep it light, but i'm not sure if you mean "keep it light for the end user" or "keep it light in implementation". In both ways tho, we can see 2 big blocks: 

1. either the type system is dumb (and simple in implementation/feature), for which a end user will have to manually write all the types (like in Rust), then the experience will not fit the "simple" JS way...

2. either the type system would have be smart enough to compensate/extrapolate/inter typings to some extend, and then i don't think there's a middle ground between nothing and TS implementation, as for now TS has still covered only a bare minimum for a type system.
