### ISSUE TITLE
`declare` block for ambient declarations (and potentially overloads)

### ISSUE THREAD

**Issue by tjjfvi** [tc39/proposal-type-annotations#66]
Per the README, this proposal currently does not reserve space for ambient declarations like
```ts
declare let x: string;

declare class Foo {
    bar(x: number): void;
}

declare function foo(): boolean;
```

As a middleground between 'no support for ambient declarations' and 'full support for ambient declarations', I propose the following syntax be added:
```ts
declare {
  [arbitrary content with balanced braces]
}
```

Then, ambient declarations could be written as
```ts
declare {
  let x: string;

  class Foo {
      bar(x: number): void;
  }

  function foo(): boolean;
}
```

Though this syntax is not currently supported in TypeScript, it seems that it would be a minor addition.

This would allow type checkers to have syntax for ambient declarations, without the spec including a fixed set of specific grammars for each current type of ambient declaration (`declare let`, `declare class`, etc.). It also makes it future-proof if type checkers come to need other kinds of ambient declarations.

Additionally, per the README, this proposal currently does not reserve space for overloads, either. Type checkers could also use the `declare` block for syntax for overloads, e.g.:
```ts
declare {
  function foo(x: number): number;
  function foo(x: string): string;
}
function foo(x: string | number): string | number {
    if (typeof x === number) {
          return x + 1
    }
    else {
        return x + "!"
    }
}
```

**Comment by harrysolovay** [comment]
This syntax would be useful in TypeScript as well. I often want to `declare` multiple values at once. Eliminating the need for `declare` repetition would be a handy convenience.

**Comment by giltayar** [comment]
My personal goal is not to improve TS or Flow. It is to make most TS programs also legal JS programs.

**Comment by tjjfvi** [comment]
They don't have that in the source files *yet*. Many files do, however, use `declare`. A common example in TS is
```ts
declare const _myTag: unique symbol; // nominal type, used for e.g. branding
```
While existing TS files using that syntax won't work, it is trivial to modify that to
```ts
declare { const _myTag: unique symbol; }
```

Many TS files will require modification to be used in this syntax anyway, as many use regular `import`s to import types (i.e. don't use `import type` everwhere). Thus, requiring a transformation be applied to certain files (in this case, `declare ...` to `declare { ... }`) is not without precedent, and it is much better than the current alternative of 'files that use declare are impossible to transform to use types-as-comments'.

**Comment by benjamingr** [comment]
Note there is an alternative - these can be defined in JSDoc comments or in declaration files the type checker would be aware of (but runtime wouldn't).

**Comment by tjjfvi** [comment]
@benjamingr Good point, I hadn't thought of moving the declare to an external declaration file. However, both of those solutions are non-ideal:
- JSDoc types aren't supported in TS files currently, and I don't see any way to make ambient declarations with JSDoc comments in the TS documentation (not sure about flow).
- Requiring ambient declarations be moved to an external declaration file means that transforming some files is no longer just a simple codemod, as files need to be broken up.

Of these three options (`declare` blocks, JSDoc comments, external declaration files), every one requires modifying existing TS files, but `declare` blocks are the least intrusive change.

**Comment by benjamingr** [comment]
> JSDoc types aren't supported in TS files currently, and I don't see any way to make ambient declarations with JSDoc comments in the TS documentation (not sure about flow).

Sure though this proposal isn't about TS files. I assume it will work in JS files or at least that's my understanding from the TS team.

**Comment by romulocintra** [comment]
Closing this one in favour of https://github.com/tc39/proposal-type-annotations/issues/4 where we continue this discussion
