### ISSUE TITLE
Propose Flow's type cast syntax in addition to TypeScript's `as`?

### ISSUE THREAD

**Issue by samwgoldman** [tc39/proposal-type-annotations#91]
The FAQ mentions this omission, under "Does this proposal make all Flow programs valid JavaScript?"

> Flow could consider modifying these in the language so that they conform to this proposal

The same section mentions that the proposal could possibly be extended to reserve room for `opaque`. Would it also be possible to reserve room for Flow's type cast syntax? What would it take to make this part of the proposal?

**Comment by giltayar** [comment]
For reference, flow's type cast syntax is `(value: Type)`.

**Comment by gkz** [comment]
Some more Flow specific syntax to support (non-exhaustive), (along with type casting `(foo: T)` and opaque types `opaque type T = ...`

Variance in classes:
```
class A {
  +x: number;
}
```
Import with `typeof`
```
import typeof A from 'a';
```
Predicate functions:
```
function truthy(a, b): boolean %checks {
  return !!a && !!b;
}
```

To consider when parsing types - optional indexed access types:
```
type T = TasksContent?.['tasks'];
```

**Comment by gkz** [comment]
Closing in favor of https://github.com/tc39/proposal-type-annotations/issues/195
